### ISSUE TITLE
missing class or uppercase package name (`org.jruby.runtime.profile.ProfilePrinter')

### ISSUE THREAD

**Issue by wilg** [justfalter/jruby-profiler-callgrind-printer#1]
Trying to use the printer as indicated in the README, but I keep running into this. Can't tell if I'm doing something wrong or if this project is out-of-date.

```
missing class or uppercase package name (`org.jruby.runtime.profile.ProfilePrinter'), caused by (NameError) cannot load Java class org.jruby.runtime.profile.ProfilePrinter
  org/jruby/javasupport/JavaUtilities.java:54:in `get_proxy_or_package_under_package'
  file:/Users/wil/.rvm/rubies/jruby-1.7.15/lib/jruby.jar!/jruby/java/java_package_module_template.rb:14:in `method_missing'
  /Users/wil/.rvm/gems/jruby-1.7.15@my-gemset/gems/jruby-profiler-callgrind-printer-1.0.0-java/lib/jruby/profiler/callgrind_printer.rb:3:in `Profiler'
  /Users/wil/.rvm/gems/jruby-1.7.15@my-gemset/gems/jruby-profiler-callgrind-printer-1.0.0-java/lib/jruby/profiler/callgrind_printer.rb:2:in `JRuby'
  /Users/wil/.rvm/gems/jruby-1.7.15@my-gemset/gems/jruby-profiler-callgrind-printer-1.0.0-java/lib/jruby/profiler/callgrind_printer.rb:1:in `(root)'
  org/jruby/RubyKernel.java:1065:in `require'
  /Users/wil/.rvm/gems/jruby-1.7.15@my-gemset/gems/backports-3.6.0/lib/backports/tools.rb:343:in `require_with_backports'
```

**Comment by cheald** [comment]
In modern versions of JRuby this has moved to `org.jruby.runtime.profile.builtin.ProfilePrinter`.
